%%
%{
filename: RamosGRL2022_MAIN.m

author: Evan J. Ramos
date:   23 July 2020

Description: this script uses the chemistry of clays in paleosols and
representative source rocks to determine the up-section weathering trends
in the Bighorn basin.

**associated with Ramos et al., 2022 Geophysical Research Letters

%}

close all
clear
clc

set(0, 'DefaultAxesFontSize', 15,...
       'DefaultLineLinewidth', 2,...
       'DefaultAxesXColor','k',...
       'DefaultAxesYColor','k')

%% Load files

%Load main data from Ramos et al., 2022 GRL
file1 = 'Table S1.xlsx';
C        = readtable(file1,'Sheet',1); %clay data
S        = readtable(file1,'Sheet',2); %source data

%Polecat Bench data (van der Muelen et al., 2020 EPSL) + global pCO2 model
%estimates across the PETM (Haynes and Honish, 2020)
file2 = 'PCB_PETM_data.xlsx';
%pCO2 model estimates
pCO2      = readtable(file2,'Sheet',1);
%Carbonate d13C
d13C      = readtable(file2,'Sheet',2);
%Elevation vs. time for PCB data
Elev_Time = readtable(file2,'Sheet',3);

%% Compute times relative to CIE for each of my samples

%units (kyr)
time_fit = polyfit(Elev_Time.Elevation_m_,Elev_Time.Time_kyr_,1);

C.Time_kyr = polyval(time_fit,...
                     C.Elevation_m_ - Elev_Time.ConversionFactor_m_(1));

%% Interpolate pCO2 curve for each sample
time        = pCO2.HH2020Time_kyr_;
co2         = pCO2.HH2020PCO2_uatm_;
sel1        = ~isnan(C.Time_kyr) & C.Time_kyr >= min(time);
sel2        = ~isnan(time);
C.pCO2      = C.Time_kyr;
C.pCO2(sel1) = interp1(time(sel2),co2(sel2),C.Time_kyr(sel1));
C.pCO2(C.Time_kyr < min(time)) = min(co2);

%% Elemental ratios

%molar values
C.mLi = C.Li_ppb_/6.941;
S.mLi = S.Li_ppb_/6.941;
C.mTi = C.Ti_ppb_/47.867;
S.mTi = S.Ti_ppb_/47.867;
C.mCs = C.Cs_ppb_/132.90545; 
S.mCs = S.Cs_ppb_/132.90545;
C.mAl = C.Al_ppb_/26.981539; 
S.mAl = S.Al_ppb_/26.981539;
C.mZr = C.Zr_ppb_/91.224;
S.mZr = S.Zr_ppb_/91.224;

%elemental ratios needed
C.LiAl = C.mLi./C.mAl*1000;
S.LiAl = S.mLi./S.mAl*1000;
C.TiAl = C.mTi./C.mAl;
S.TiAl = S.mTi./S.mAl;
C.CsAl = C.mCs./C.mAl*1000;
S.CsAl = S.mCs./S.mAl*1000;
C.ZrAl = C.mZr./C.mAl*1000;
S.ZrAl = S.mZr./S.mAl*1000;

rat_err = sqrt(0.06^2 + 0.12^2); 
%this value arises from the average 1sig error on standards
               %during the same run as these data. When the error is
               %propagated, you get a value that is equal to the error *
               %sqrt(2).

%% Select end points for fits

igneous_sample1 = 'BHB-BTC-B';   
igneous_sample2 = 'BHB-BTC-F';   ig = strcmp(S.SampleName,igneous_sample1)|...
                                      strcmp(S.SampleName,igneous_sample2);
shale_sample    = 'AAB 1111';    sh = strcmp(S.SampleName,shale_sample);
                                 cg = strcmp(S.SampleType,'Conglomerate');
                                 Sh = strcmp(S.SampleType,'Shale');
                                 cu = strcmp(C.SoilFacies,'cumulative');
                                 co = strcmp(C.SoilFacies,'composite');
                                 cr = strcmp(C.SoilFacies,'crevasse');
                                
%% Determine Li/Al_source and d7Li_source

%The source rock compositions are going to be found two different ways
%Method 1: Fit of Cs/Al and Zr/Al data
%Method 2: Fit of Ti/Al and Cs/Al data

Li_source = zeros(height(C),3); %3 columns for 3 techniques
d7Li_source = zeros(height(C),3); %3 columns for 3 techniques

%%%%%%%%%%% Method 1: Zr/Al vs Cs/Al
ig_coord1 = [mean(S.CsAl(ig)) mean(S.ZrAl(ig))]; 
sh_coord1 = [S.CsAl(sh) S.ZrAl(sh)];

cl_coord1 = zeros(height(C),2);
cl_coord1(:,1) = C.CsAl; cl_coord1(:,2) = C.ZrAl;

[perc_ig1, perc_sh1, s1] = percent_distance(ig_coord1,...
                                            sh_coord1,...
                                            cl_coord1);
                                    
%%%%%%%%%%% Method 2: Cs/Al vs Ti/Al
ig_coord2 = [mean(S.TiAl(ig)) mean(S.CsAl(ig))]; 
sh_coord2 = [S.TiAl(sh) S.CsAl(sh)];

cl_coord2 = zeros(height(C),2);
cl_coord2(:,1) = C.TiAl; cl_coord2(:,2) = C.CsAl;

[perc_ig2, perc_sh2, s2] = percent_distance(ig_coord2,...
                                            sh_coord2,...
                                            cl_coord2);
                                    
%%%%%%%%%%% Method 3: Zr/Al vs Ti/Al
ig_coord3 = [mean(S.TiAl(ig)) mean(S.ZrAl(ig))]; 
sh_coord3 = [S.TiAl(sh) S.ZrAl(sh)];

cl_coord3 = zeros(height(C),2);
cl_coord3(:,1) = C.TiAl; cl_coord3(:,2) = C.ZrAl;

[perc_ig3, perc_sh3, s3] = percent_distance(ig_coord3,...
                                            sh_coord3,...
                                            cl_coord3);
                                    
%%%%% Compute source Li/Al and Li/Al-weighted source D7Li

Li_source(:,1) = mean(S.LiAl(ig))*perc_ig1 + S.LiAl(sh)*perc_sh1; 
Li_source(:,2) = mean(S.LiAl(ig))*perc_ig2 + S.LiAl(sh)*perc_sh2;
Li_source(:,3) = mean(S.LiAl(ig))*perc_ig3 + S.LiAl(sh)*perc_sh3;

d7Li_source(:,1) = (mean(S.LiAl(ig).*S.x_7Li__LSVEC_(ig))*perc_ig1 + ...
                    S.LiAl(sh)*S.x_7Li__LSVEC_(sh)*perc_sh1)./Li_source(:,1);
d7Li_source(:,2) = (mean(S.LiAl(ig).*S.x_7Li__LSVEC_(ig))*perc_ig2 + ...
                    S.LiAl(sh)*S.x_7Li__LSVEC_(sh)*perc_sh2)./Li_source(:,2);
d7Li_source(:,3) = (mean(S.LiAl(ig).*S.x_7Li__LSVEC_(ig))*perc_ig3 + ...
                    S.LiAl(sh)*S.x_7Li__LSVEC_(sh)*perc_sh3)./Li_source(:,3);

D7Li = [C.x_7Li__LSVEC_ C.x_7Li__LSVEC_ C.x_7Li__LSVEC_] - d7Li_source;

%% Immobile element mixing plots

%colormap for shale samples
shale_cols = [127 201 127;... %Mesa Verde
              190 174 212;... %Cody 
              253 192 134;... %Thermopolis/Mowry
              255 255 153]... %Gypsum Springs/Morrison/Cloverly
              /255;

%logical indices for shale units
mv   = strcmp(S.Formation,'Mesa Verde');
cody = strcmp(S.Formation,'Cody');
tm   = strcmp(S.Formation,'Thermopolis/Mowry');
gmc  = strcmp(S.Formation,'Gypsum Springs/Morrison/Cloverly');

%logical indices for conglomerate lithologies
igs  = strcmp(S.Lithology,'Igneous');
carb = strcmp(S.Lithology,'Carbonate');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Zr/Al vs. Cs/Al
figure

%clay
errorbar(C.CsAl,...
         C.ZrAl,rat_err*C.ZrAl,...
                rat_err*C.ZrAl,...
                rat_err*C.CsAl,...
                rat_err*C.CsAl,...
         'ko','MarkerSize',12,'MarkerFaceColor','w','CapSize',0); 
         hold on;

%conglomerate
errorbar(S.CsAl(igs),...
         S.ZrAl(igs),rat_err*S.ZrAl(igs),...
                     rat_err*S.ZrAl(igs),...
                     rat_err*S.CsAl(igs),...
                     rat_err*S.CsAl(igs),...
         'kd','MarkerSize',12,'MarkerFaceColor','k','CapSize',0)
     
errorbar(S.CsAl(carb),...
         S.ZrAl(carb),rat_err*S.ZrAl(carb),...
                      rat_err*S.ZrAl(carb),...
                      rat_err*S.CsAl(carb),...
                      rat_err*S.CsAl(carb),...
         'kd','MarkerSize',12,'MarkerFaceColor','w','CapSize',0)

%shale
errorbar(S.CsAl(mv),...
         S.ZrAl(mv),rat_err*S.ZrAl(mv),...
                    rat_err*S.ZrAl(mv),...
                    rat_err*S.CsAl(mv),...
                    rat_err*S.CsAl(mv),...
         'k^','MarkerSize',12,'MarkerFaceColor',shale_cols(1,:),'CapSize',0)

errorbar(S.CsAl(cody),...
         S.ZrAl(cody),rat_err*S.ZrAl(cody),...
                      rat_err*S.ZrAl(cody),...
                      rat_err*S.CsAl(cody),...
                      rat_err*S.CsAl(cody),...
         'k^','MarkerSize',12,'MarkerFaceColor',shale_cols(2,:),'CapSize',0)

errorbar(S.CsAl(tm),...
         S.ZrAl(tm),rat_err*S.ZrAl(tm),...
                    rat_err*S.ZrAl(tm),...
                    rat_err*S.CsAl(tm),...
                    rat_err*S.CsAl(tm),...
         'k^','MarkerSize',12,'MarkerFaceColor',shale_cols(3,:),'CapSize',0)
     
errorbar(S.CsAl(gmc),...
         S.ZrAl(gmc),rat_err*S.ZrAl(gmc),...
                     rat_err*S.ZrAl(gmc),...
                     rat_err*S.CsAl(gmc),...
                     rat_err*S.CsAl(gmc),...
         'k^','MarkerSize',12,'MarkerFaceColor',shale_cols(4,:),'CapSize',0)

%linear fit + error envelope
X1 = [S.CsAl(ig); S.CsAl(sh); C.CsAl];
Y1 = [S.ZrAl(ig); S.ZrAl(sh); C.ZrAl];

[p, saxipbi, xplot, low_alpha, high_alpha, ~] = ...
  linfitxy(X1, Y1, rat_err*X1, rat_err*Y1,'NSigma',1);
x_corr = xplot >= min(X1) & xplot <= max(X1);
xplot = xplot(x_corr);
saxipbi = saxipbi(:,x_corr);

patch([xplot fliplr(xplot)],...
      [saxipbi(low_alpha,:) fliplr(saxipbi(high_alpha,:))],...
      [.5 .5 .5],'FaceAlpha',1,'EdgeColor','none','HandleVisibility','off')
plot([min(xplot),max(xplot)], p(1)*[min(xplot),max(xplot)]+p(2),...
     'Color','k')

xlabel('Cs/Al (mol/mol) $\times$ 1000 ','interpreter','latex')
ylabel('Zr/Al (mol/mol) $\times$ 1000','interpreter','latex')
set(gca,'TickLabelInterpreter','Latex')
legend('Clay','Igneous','Carbonate-siliciclastic','Mesa Verde','Cody',...
       'Thermopolis/Mowry','Gypsum Springs/Morrison/Cloverly','Best fit',...
       'interpreter','latex')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Ti/Al vs. Cs/Al
figure

%clay
errorbar(C.CsAl,...
         C.TiAl,rat_err*C.TiAl,...
                rat_err*C.TiAl,...
                rat_err*C.CsAl,...
                rat_err*C.CsAl,...
         'ko','MarkerSize',12,'MarkerFaceColor','w','CapSize',0); 
         hold on;

%conglomerate
errorbar(S.CsAl(igs),...
         S.TiAl(igs),rat_err*S.TiAl(igs),...
                     rat_err*S.TiAl(igs),...
                     rat_err*S.CsAl(igs),...
                     rat_err*S.CsAl(igs),...
         'kd','MarkerSize',12,'MarkerFaceColor','k','CapSize',0)
     
errorbar(S.CsAl(carb),...
         S.TiAl(carb),rat_err*S.TiAl(carb),...
                      rat_err*S.TiAl(carb),...
                      rat_err*S.CsAl(carb),...
                      rat_err*S.CsAl(carb),...
         'kd','MarkerSize',12,'MarkerFaceColor','w','CapSize',0)

%shale
errorbar(S.CsAl(mv),...
         S.TiAl(mv),rat_err*S.TiAl(mv),...
                    rat_err*S.TiAl(mv),...
                    rat_err*S.CsAl(mv),...
                    rat_err*S.CsAl(mv),...
         'k^','MarkerSize',12,'MarkerFaceColor',shale_cols(1,:),'CapSize',0)

errorbar(S.CsAl(cody),...
         S.TiAl(cody),rat_err*S.TiAl(cody),...
                      rat_err*S.TiAl(cody),...
                      rat_err*S.CsAl(cody),...
                      rat_err*S.CsAl(cody),...
         'k^','MarkerSize',12,'MarkerFaceColor',shale_cols(2,:),'CapSize',0)

errorbar(S.CsAl(tm),...
         S.TiAl(tm),rat_err*S.TiAl(tm),...
                    rat_err*S.TiAl(tm),...
                    rat_err*S.CsAl(tm),...
                    rat_err*S.CsAl(tm),...
         'k^','MarkerSize',12,'MarkerFaceColor',shale_cols(3,:),'CapSize',0)
     
errorbar(S.CsAl(gmc),...
         S.TiAl(gmc),rat_err*S.TiAl(gmc),...
                     rat_err*S.TiAl(gmc),...
                     rat_err*S.CsAl(gmc),...
                     rat_err*S.CsAl(gmc),...
         'k^','MarkerSize',12,'MarkerFaceColor',shale_cols(4,:),'CapSize',0)

%linear fit + error envelope
X2 = [S.CsAl(ig); S.CsAl(sh); C.CsAl];
Y2 = [S.TiAl(ig); S.TiAl(sh); C.TiAl];

[p, saxipbi, xplot, low_alpha, high_alpha, ~] = ...
  linfitxy(X2, Y2, rat_err*X2, rat_err*Y2,'NSigma',1);
x_corr = xplot >= min(X2) & xplot <= max(X2);
xplot = xplot(x_corr);
saxipbi = saxipbi(:,x_corr);

patch([xplot fliplr(xplot)],...
      [saxipbi(low_alpha,:) fliplr(saxipbi(high_alpha,:))],...
      [.5 .5 .5],'FaceAlpha',1,'EdgeColor','none','HandleVisibility','off')
plot([min(xplot),max(xplot)], p(1)*[min(xplot),max(xplot)]+p(2),...
     'Color','k')
     
xlabel('Cs/Al (mol/mol) $\times$ 1000','interpreter','latex')
ylabel('Ti/Al (mol/mol)','interpreter','latex')
set(gca,'TickLabelInterpreter','Latex')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Zr/Al vs. Ti/Al
figure

%clay
errorbar(C.TiAl,...
         C.ZrAl,rat_err*C.ZrAl,...
                rat_err*C.ZrAl,...
                rat_err*C.TiAl,...
                rat_err*C.TiAl,...
         'ko','MarkerSize',12,'MarkerFaceColor','w','CapSize',0); 
         hold on;

%conglomerate
errorbar(S.TiAl(igs),...
         S.ZrAl(igs),rat_err*S.ZrAl(igs),...
                     rat_err*S.ZrAl(igs),...
                     rat_err*S.TiAl(igs),...
                     rat_err*S.TiAl(igs),...
         'kd','MarkerSize',12,'MarkerFaceColor','k','CapSize',0)
     
errorbar(S.TiAl(carb),...
         S.ZrAl(carb),rat_err*S.ZrAl(carb),...
                      rat_err*S.ZrAl(carb),...
                      rat_err*S.TiAl(carb),...
                      rat_err*S.TiAl(carb),...
         'kd','MarkerSize',12,'MarkerFaceColor','w','CapSize',0)

%shale
errorbar(S.TiAl(mv),...
         S.ZrAl(mv),rat_err*S.ZrAl(mv),...
                    rat_err*S.ZrAl(mv),...
                    rat_err*S.TiAl(mv),...
                    rat_err*S.TiAl(mv),...
         'k^','MarkerSize',12,'MarkerFaceColor',shale_cols(1,:),'CapSize',0)

errorbar(S.TiAl(cody),...
         S.ZrAl(cody),rat_err*S.ZrAl(cody),...
                      rat_err*S.ZrAl(cody),...
                      rat_err*S.TiAl(cody),...
                      rat_err*S.TiAl(cody),...
         'k^','MarkerSize',12,'MarkerFaceColor',shale_cols(2,:),'CapSize',0)

errorbar(S.TiAl(tm),...
         S.ZrAl(tm),rat_err*S.ZrAl(tm),...
                    rat_err*S.ZrAl(tm),...
                    rat_err*S.TiAl(tm),...
                    rat_err*S.TiAl(tm),...
         'k^','MarkerSize',12,'MarkerFaceColor',shale_cols(3,:),'CapSize',0)
     
errorbar(S.TiAl(gmc),...
         S.ZrAl(gmc),rat_err*S.ZrAl(gmc),...
                     rat_err*S.ZrAl(gmc),...
                     rat_err*S.TiAl(gmc),...
                     rat_err*S.TiAl(gmc),...
         'k^','MarkerSize',12,'MarkerFaceColor',shale_cols(4,:),'CapSize',0)

%linear fit + error envelope
X3 = [S.TiAl(ig); S.TiAl(sh); C.TiAl];
Y3 = [S.ZrAl(ig); S.ZrAl(sh); C.ZrAl];

[p, saxipbi, xplot, low_alpha, high_alpha, sp] = ...
  linfitxy(X3, Y3, rat_err*X3, rat_err*Y3,'NSigma',1);
x_corr = xplot >= min(X3) & xplot <= max(X3);
xplot = xplot(x_corr);
saxipbi = saxipbi(:,x_corr);

patch([xplot fliplr(xplot)],...
      [saxipbi(low_alpha,:) fliplr(saxipbi(high_alpha,:))],...
      [.5 .5 .5],'FaceAlpha',1,'EdgeColor','none','HandleVisibility','off')
plot([min(xplot),max(xplot)], p(1)*[min(xplot),max(xplot)]+p(2),...
     'Color','k')
 
xlabel('Ti/Al (mol/mol)','interpreter','latex')
ylabel('Zr/Al (mol/mol) $\times$ 1000','interpreter','latex')
set(gca,'TickLabelInterpreter','Latex')

%% Determine best fit mixing model

%model1: Zr/Al vs. Cs/Al
[~,~,~,~,stats1] = regress(Y1,[ones(size(X1)) X1]);

%model2: Ti/Al vs. Cs/Al
[~,~,~,~,stats2] = regress(Y2,[ones(size(X2)) X2]);

%model3: Zr/Al vs. Ti/Al
[~,~,~,~,stats3] = regress(Y3,[ones(size(X3)) X3]);

%Find best model
R2 = [stats1(1) stats2(1) stats3(1)];
[~,modelbest] = max(R2);

clc
disp('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
fprintf('\n\nBest fit: Model %d\n\n\n',modelbest)
disp('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')

%% Plot vs. time

set(0,'DefaultAxesFontSize',15)
figure
subplot(4,1,1)
plot(pCO2.HH2020Time_kyr_,pCO2.HH2020PCO2_uatm_,'-','color',[.5 .5 .5])
ylabel('$p$CO$_2$ ($\mu$atm)','interpreter','latex')
xlim([-50 150]); ylim([500 3000])
set(gca,'ticklabelinterpreter','latex','xticklabel',[])

subplot(4,1,2)
ff = fit(d13C.Time_kyr_,d13C.d13C,'smoothingspline','SmoothingParam',.025);
pp = plot(ff,d13C.Time_kyr_,d13C.d13C); legend off
pp(1).Color= [.5 .5 .5];
pp(2).Color= 'k';
xlim([-50 150])
ylim([-16 -6])
xlabel('')
ylabel('$\delta^{13}$C','interpreter','latex')
set(gca,'ticklabelinterpreter','latex','xticklabel',[])

subplot(4,1,3)
errorbar(C.Time_kyr,D7Li(:,modelbest),...
                        .5*sqrt(2)*ones(height(C),1),...
                        'ko','MarkerFaceColor','w',...
                        'CapSize',0); hold on;
fff = fit(C.Time_kyr,D7Li(:,modelbest),'smoothingspline','SmoothingParam',.025);
ppp = plot(fff,C.Time_kyr,D7Li(:,modelbest)); legend off
ppp(1).Marker = 'none';
ppp(2).Color= 'k';
ylabel('$\Delta^7$Li$_{\mathrm{clay-source}}$','interpreter','latex')
xlabel('')
set(gca,'ticklabelinterpreter','latex','xticklabel',[])
ylim([-4 0])
xlim([-50 150])

subplot(4,1,4)
errorbar(C.Time_kyr,perc_sh2,...
                        zeros(height(C),1),...
                        'ko','MarkerFaceColor','w',...
                        'CapSize',0); hold on;
fff = fit(C.Time_kyr,perc_sh2,'smoothingspline','SmoothingParam',.025);
ppp = plot(fff,C.Time_kyr,perc_sh2); legend off
ppp(1).Marker = 'none';
ppp(2).Color= 'k';
ylabel('f$_{\mathrm{shale}}$','interpreter','latex')
xlabel('Time (kyr)','interpreter','latex')
set(gca,'ticklabelinterpreter','latex')
ylim([.2 1])
xlim([-50 150])

%% Selection criteria for soils

ped_labels  = C.SoilFacies;
time_labels = C.TimeInterval;
ped.cr      = strcmp(ped_labels,'crevasse');
ped.co      = strcmp(ped_labels,'composite');
ped.cu      = strcmp(ped_labels,'cumulative');
ped.pre     = strcmp(time_labels,'pre-onset');
ped.syn     = strcmp(time_labels,'onset') | ...
              strcmp(time_labels,'main body');
ped.post    = strcmp(time_labels,'recovery');


%% Plot D7Li vs. fshale by soil type

xmin = .2;
xmax = 1;
%linear fits by soil type 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[Cr_fit_pre, Saxipbi.cr_pre, Xplot.cr_pre, Low_alpha.cr_pre, High_alpha.cr_pre, Sp.cr_pre]  ...
    = linfitxy(perc_sh2(ped.cr&ped.pre),...
                       D7Li(ped.cr&ped.pre,modelbest),...
                       zeros(sum(ped.cr&ped.pre),1),...
                       .5*ones(sum(ped.cr&ped.pre),1),'NSigma',1);  
                   
X_corr.cr_pre = Xplot.cr_pre >= xmin & Xplot.cr_pre <= xmax;
Xplot.cr_pre = Xplot.cr_pre(X_corr.cr_pre);
Saxipbi.cr_pre = Saxipbi.cr_pre(:,X_corr.cr_pre);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[Cr_fit_rest, Saxipbi.cr_rest, Xplot.cr_rest, Low_alpha.cr_rest, High_alpha.cr_rest, Sp.cr_rest]  ... 
    = linfitxy(perc_sh2(ped.cr&~ped.pre),...
                       D7Li(ped.cr&~ped.pre,modelbest),...
                       zeros(sum(ped.cr&~ped.pre),1),...
                       .5*ones(sum(ped.cr&~ped.pre),1),'NSigma',1);
                   
X_corr.cr_rest = Xplot.cr_rest >= xmin & Xplot.cr_rest <= xmax;
Xplot.cr_rest = Xplot.cr_rest(X_corr.cr_rest);
Saxipbi.cr_rest = Saxipbi.cr_rest(:,X_corr.cr_rest);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[Co_fit, Saxipbi.co, Xplot.co, Low_alpha.co, High_alpha.co, Sp.co] ...
    = linfitxy(perc_sh2(ped.co),...
                       D7Li(ped.co,modelbest),...
                       zeros(sum(ped.co),1),...
                       .5*ones(sum(ped.co),1),'NSigma',1);
                   
X_corr.co = Xplot.co >= xmin & Xplot.co <= xmax;
Xplot.co = Xplot.co(X_corr.co);
Saxipbi.co = Saxipbi.co(:,X_corr.co);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[Cu_fit_pre, Saxipbi.cu_pre, Xplot.cu_pre, Low_alpha.cu_pre, High_alpha.cu_pre, Sp.cu_pre]  ...
    = linfitxy(perc_sh2(ped.cu&ped.pre),...
                       D7Li(ped.cu&ped.pre,modelbest),...
                       zeros(sum(ped.cu&ped.pre),1),...
                       .5*ones(sum(ped.cu&ped.pre),1),'NSigma',1);

X_corr.cu_pre = Xplot.cu_pre >= xmin & Xplot.cu_pre <= xmax;
Xplot.cu_pre = Xplot.cu_pre(X_corr.cu_pre);
Saxipbi.cu_pre = Saxipbi.cu_pre(:,X_corr.cu_pre);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[Cu_fit_rest, Saxipbi.cu_rest, Xplot.cu_rest, Low_alpha.cu_rest, High_alpha.cu_rest, Sp.cu_rest]  ... 
    = linfitxy(perc_sh2(ped.cu&~ped.pre),...
                       D7Li(ped.cu&~ped.pre,modelbest),...
                       zeros(sum(ped.cu&~ped.pre),1),...
                       .5*ones(sum(ped.cu&~ped.pre),1),'NSigma',1);
                   
X_corr.cu_rest = Xplot.cu_rest >= xmin & Xplot.cu_rest <= xmax;
Xplot.cu_rest = Xplot.cu_rest(X_corr.cu_rest);
Saxipbi.cu_rest = Saxipbi.cu_rest(:,X_corr.cu_rest);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%compute R2
[~,~,~,~,cr_stats_pre]  = regress(...
                          D7Li(ped.cr&ped.pre,modelbest),...
                          [ones(sum(ped.cr&ped.pre),1) ...
                          perc_sh2(ped.cr&ped.pre)]);
[~,~,~,~,cr_stats_rest] = regress(...
                          D7Li(ped.cr&~ped.pre,modelbest),...
                          [ones(sum(ped.cr&~ped.pre),1) ...
                          perc_sh2(ped.cr&~ped.pre)]);
[~,~,~,~,co_stats]      = regress(...
                          D7Li(ped.co,modelbest),...
                          [ones(sum(ped.co),1) ...
                          perc_sh2(ped.co)]);
[~,~,~,~,cu_stats_pre]  = regress(...
                          D7Li(ped.cu&ped.pre,modelbest),...
                          [ones(sum(ped.cu&ped.pre),1) ...
                          perc_sh2(ped.cu&ped.pre)]);
[~,~,~,~,cu_stats_rest] = regress(...
                          D7Li(ped.cu&~ped.pre,modelbest),...
                          [ones(sum(ped.cu&~ped.pre),1) ...
                          perc_sh2(ped.cu&~ped.pre)]);

%generate plot
figure

%%%%%%%%%%%%%%%%%%%%%%% ERROR ENVELOPES %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
patch([Xplot.cr_pre fliplr(Xplot.cr_pre)],...
      [Saxipbi.cr_pre(Low_alpha.cr_pre,:) fliplr(Saxipbi.cr_pre(High_alpha.cr_pre,:))],...
      'g','FaceAlpha',.5,'EdgeColor','none','HandleVisibility','off')

hold on

patch([Xplot.cr_rest fliplr(Xplot.cr_rest)],...
      [Saxipbi.cr_rest(Low_alpha.cr_rest,:) fliplr(Saxipbi.cr_rest(High_alpha.cr_rest,:))],...
      'g','FaceAlpha',.5,'EdgeColor','none','HandleVisibility','off')
  
patch([Xplot.co fliplr(Xplot.co)],...
      [Saxipbi.co(Low_alpha.co,:) fliplr(Saxipbi.co(High_alpha.co,:))],...
      'b','FaceAlpha',.5,'EdgeColor','none','HandleVisibility','off')
  
patch([Xplot.cu_pre fliplr(Xplot.cu_pre)],...
      [Saxipbi.cu_pre(Low_alpha.cu_pre,:) fliplr(Saxipbi.cu_pre(High_alpha.cu_pre,:))],...
      'r','FaceAlpha',.5,'EdgeColor','none','HandleVisibility','off')

patch([Xplot.cu_rest fliplr(Xplot.cu_rest)],...
      [Saxipbi.cu_rest(Low_alpha.cu_rest,:) fliplr(Saxipbi.cu_rest(High_alpha.cu_rest,:))],...
      'r','FaceAlpha',.5,'EdgeColor','none','HandleVisibility','off')

%%%%%%%%%%%%%%%%%%%%%%%%%%% DATA POINTS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
errorbar(perc_sh2(ped.cr&ped.pre),D7Li(ped.cr&ped.pre,modelbest),...
                                  .5*ones(sum(ped.cr&ped.pre),1),...
                                  'markersize',10,...
                                  'marker','o',...
                                  'color','k',...
                                  'linestyle','none',...
                                  'markeredgecolor','k',...
                                  'markerfacecolor','g',...
                                  'Capsize',0)
hold on                                 

errorbar(perc_sh2(ped.cr&~ped.pre),D7Li(ped.cr&~ped.pre,modelbest),...
                                  .5*ones(sum(ped.cr&~ped.pre),1),...
                                  'markersize',10,...
                                  'marker','d',...
                                  'color','k',...                                 
                                  'linestyle','none',...
                                  'markeredgecolor','k',...
                                  'markerfacecolor','g',...
                                  'Capsize',0)
errorbar(perc_sh2(ped.co),D7Li(ped.co,modelbest),...
                          .5*ones(sum(ped.co),1),...
                          'markersize',10,...
                          'marker','d',...
                          'color','k',...
                          'linestyle','none',...
                          'markeredgecolor','k',...
                          'markerfacecolor','b',...
                          'Capsize',0)
errorbar(perc_sh2(ped.cu&ped.pre),D7Li(ped.cu&ped.pre,modelbest),...
                                  .5*ones(sum(ped.cu&ped.pre),1),...
                                  'markersize',10,...
                                  'marker','o',...
                                  'color','k',...
                                  'linestyle','none',...
                                  'markeredgecolor','k',...
                                  'markerfacecolor','r',...
                                  'Capsize',0)
errorbar(perc_sh2(ped.cu&~ped.pre),D7Li(ped.cu&~ped.pre,modelbest),...
                                  .5*ones(sum(ped.cu&~ped.pre),1),...
                                  'markersize',10,...
                                  'marker','d',...
                                  'color','k',...
                                  'linestyle','none',...
                                  'markeredgecolor','k',...
                                  'markerfacecolor','r',...
                                  'Capsize',0)
 
sh_fit = linspace(0.2,1);
plot(sh_fit,polyval(Cr_fit_pre,sh_fit),'g-','HandleVisibility','off')
plot(sh_fit,polyval(Cr_fit_rest,sh_fit),'g-.','HandleVisibility','off')
plot(sh_fit,polyval(Co_fit,sh_fit),'b-.','HandleVisibility','off')
plot(sh_fit,polyval(Cu_fit_pre,sh_fit),'r-','HandleVisibility','off')
plot(sh_fit,polyval(Cu_fit_rest,sh_fit),'r-.','HandleVisibility','off')

xlabel('f$_{\mathrm{shale}}$','interpreter','latex')
ylabel('$\Delta^7$Li$_{\mathrm{clay-source}}$','interpreter','latex')
set(gca,'ticklabelinterpreter','latex')
legend('Crevasse splay: pre-onset + onset','Crevasse splay: main body + recovery',...
       'Composite','Cumulative: pre-onset + onset','Cumulative: main body + recovery',...
       'interpreter','latex','fontsize',12,'location','northwest')
legend boxoff
xlim([0.2 1])